name: cref
channels:
  - defaults
  - conda-forge
dependencies:
  - fuzzywuzzy=0.17.0
  - ipykernel=5.1.4
  - ipympl=0.3.3
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jupyter_client=6.1.3
  - jupyter_core=4.6.3
  - mms-python-client=3.4.2.1
  - networkx=2.4
  - nltk=3.4.5
  - notebook=6.0.3
  - numpy=1.18.1
  - pip=20.0.2
  - python-levenshtein=0.12.0
  - scipy=1.4.1
  - spacy=2.2.4
  - sparqlwrapper=1.8.5
  - pip:
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.0/en_core_web_sm-2.2.0.tar.gz
    - gremlinpython==3.4.7
    - tornado==4.5.3
prefix: /home/jovyan/my-conda-envs/cref

